# Read the documentation: https://github.com/FriendsOfSymfony/FOSElasticaBundle/blob/master/doc/setup.md
fos_elastica:
    clients:
        default: { url: '%env(ELASTICSEARCH_URL)%' }
    indexes:
        book:
            persistence:
                driver: orm
                model: App\Entity\Book
                provider: ~
                finder: ~
                elastica_to_model_transformer:
                    query_builder_method: createSearchQueryBuilder
                repository: App\ElasticRepository\BookRepository
            properties:
                id:
                    type: integer
                name: ~
                author:
                    type: object
                    properties:
                        name:
                            type: keyword
                reviews:
                    type: nested
                    properties:
                        rating:
                            type: integer
