# Read the documentation: https://github.com/FriendsOfSymfony/FOSElasticaBundle/blob/master/doc/setup.md
fos_elastica:
    clients:
        default: { url: '%env(ELASTICSEARCH_URL)%' }
    indexes:
        book:
            persistence:
                driver: orm
                model: App\Entity\Book
                provider: ~
                finder: ~
            properties:
                name: ~
