settings:
    number_of_replicas: 0
    number_of_shards: 1
    refresh_interval: 60s
mappings:
    dynamic: false
    properties:
        id: &entity_id
            type: unsigned_long
        name: &simple_text
            type: text
        authorId: *entity_id
        authorName: *simple_text
